load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "runfiles",
    srcs = [
        "runfiles.go",
    ],
    importpath = "github.com/bazelbuild/rules_go/go/tools/bazel/runfiles",
    visibility = ["//visibility:public"],
)

